I.see("Minha Campanha");
I.see("Convide seus amigos para apoiar sua campanha");
I.see("Facebook");
I.see("Messenger");
I.see("Status: NO AR");
I.see("Visitantes");
I.see("Apoiadores");
I.see("R$ 0,00");
I.see("Arrecadados");
I.see("0,00%");
I.see("da Meta");
I.see("Os dados podem levar até 24 horas para serem atualizados. Saiba mais.");
I.see("Visitas por dia");
I.see("Assim que visitantes começarem a aparecer você terá acesso a um gráfico aqui com o número de visitas por dia. Com isso, você terá um controle diário de quantas pessoas visitam seu projeto.");
I.see("R$ arrecadados por dia");
I.see("Assim que os apoios começarem a aparecer você terá acesso a um gráfico aqui com o total de R$ arrecadados dia a dia. Com isso, você terá um controle diário de quanto falta para você atingir a sua meta de arrecadação.");
I.see("Apoios confirmados por dia");
I.see("Você ainda não tem nenhum apoio ao seu projeto. Assim que os apoios começarem a aparecer você terá acesso a um gráfico aqui com o total de apoios confirmados dia a dia. Boa sorte!");
I.see("Origem dos apoios"); 
I.see("Assim que os apoios começarem a aparecer você terá acesso a uma tabela aqui com a origem dos seus apoios. Com isso você poderá medir suas ações de comunicação e marketing da campanha!");
I.see("Localização geográfica dos apoios");
I.see("Assim que os apoios começarem a aparecer você terá acesso a uma tabela aqui com a localização geográfica dos seus apoiadores. Com isso você pode saber de que parte do país estão vindo os seus principais colaboradores!");
I.see("Total de pessoas que clicaram no botão Lembrar-me");
I.see("Um lembrete por email é enviado antes do término da sua campanha, convidando as pessoas a apoiarem na reta final!");