I.click("#dashboard_home_link");
I.see("Olá, Time Produto Catarse!");
I.see("Este é o retrato de sua campanha hoje");
I.see("Metas");
I.see("0%");
I.see("Meta-título-200");
I.see("R$0 de R$200 por mês");
I.see("Assinaturas ativas");
I.see("0");
I.see("Receita Mensal");
I.see("R$0,00");
I.see("Saldo");  
I.see("Sacar");
I.see("Convide seus amigos para apoiar sua campanha");
I.see("Facebook");
I.see("Messenger");
I.see("Receita média por assinatura");
I.see("Novos Assinantes");
I.see("Nova receita");
I.see("Visitas por dia");
I.see("Últimos 30 dias");
I.see("Assim que visitantes começarem a aparecer você terá acesso a um gráfico aqui com o número de visitas por dia. Com isso, você terá um controle diário de quantas pessoas visitam seu projeto.");
I.see("Novas assinaturas por dia (R$)");
I.see("Você não ganhou nenhum novo assinante nos últimos 30 dias. Veja algumas dicas de ouro de realizadores de Assinaturas do Catarse que podem te ajudar a conquistar assinantes!");
I.see("Novas assinaturas por dia");
I.see("Você não ganhou nenhum novo assinante nos últimos 30 dias. Veja algumas dicas de ouro de realizadores de Assinaturas do Catarse que podem te ajudar a conquistar assinantes!");
I.wait(3);
I.see(".table-outer");
I.see("Pagamentos confirmados por mês");
I.see("Mês");
I.see("Pagamentos confirmados de Novas Assinaturas ");
I.see("Arrecadação com Novas Assinaturas");
I.see("Pagamentos confirmados totais");
I.see("Arrecadação total");