I.see("Sua campanha está no ar. Vamos agora receber doações.")
I.click("Comece a compartilhar")
I.see("Facebook")
I.see("Messenger")
I.see("Twitter")
I.see("Whatsapp")
I.see("Email")
I.see("Link da campanha")
I.click("Próximo")
I.see("Divulgar sua campanha é super importante!")
I.click("Voltar e compartilhar mais")
I.see("Facebook")
I.see("Messenger")
I.see("Twitter")
I.see("Whatsapp")
I.see("Email")
I.see("Link da campanha")
I.click("Próximo")
I.click("Gerenciar campanha")